# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI & Manual Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      version_ref:
        description: 'Commit SHA hoặc Tag cần deploy (ví dụ: 1.2.3 hoặc a1b2c3d)'
        required: true
      environment:
        description: 'Chọn môi trường deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          - development


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Get Tag
        id: get_tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF#refs/tags/}"

      - name: Create .env file
        run: |
          sed -i "s#__APP_VERSION__#${VERSION}#g" apps/app1/src/environments/environment.production.ts

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - run: npm test
      - run: npm run build --if-present
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./dist/apps/app1
          prod: true
