# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Checks Pull Request & Release

on:
  push:
    branches: ['main']
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Get Tag
        id: get_tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF#refs/tags/}"

      - name: Create .env file
        run: |
          mkdir -p apps/app1/src/environments
          echo "export const environment = {
            production: true,
            appVersion: '${VERSION}'
          };" > apps/app1/src/environments/environment.production.ts
          
      - run: npm ci --legacy-peer-deps
      - run: npm run build --if-present
      - run: npm test
